version: '3.9'

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
      - redis
    env_file:
      - .env
    

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_test:
    container_name: flask_test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - flask_db
    volumes:
      - .:/app
    command: pytest --disable-warnings

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"


volumes:
  pgdata: {}
